### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by NoxInmortus** [PrivateBin/docker-nginx-fpm-alpine#36]
Hello, coming back for my regular issue !

With latest image privatebin/nginx-fpm-alpine :

Logs does not print anything usable for me :
```
[05-May-2021 15:26:11] NOTICE: fpm is running, pid 39
[05-May-2021 15:26:11] NOTICE: ready to handle connections
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-supervise php-fpm8: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
s6-svscan: warning: unable to iopause: Invalid argument
s6-svscan: warning: executing into .s6-svscan/crash
[s6-init] ensuring user provided files have correct perms...s6-svscan panicked! Dropping to a root shell.

/bin/sh: can't access tty; job control turned off
/run/s6/services $
```
Any lead ?

**Comment by elrido** [comment]
I tried to reproduce, but it still seems to work just fine for me. Can you provide more details about your setup? Do use use userid namespace remappings, selinux, underlying filesystem type, type or version of container run time? For reference, the below was run on an Ubuntu 20.04 host on an ext4 backed root fs:

```
$ docker pull privatebin/nginx-fpm-alpine
Using default tag: latest
latest: Pulling from privatebin/nginx-fpm-alpine
540db60ca938: Already exists 
f715a5846cbe: Pull complete 
9ddd2b82170c: Pull complete 
Digest: sha256:8d851263de27992ae027550f0dfc9cee294540c5a4327fe75fc072ccbb799dca
Status: Downloaded newer image for privatebin/nginx-fpm-alpine:latest
docker.io/privatebin/nginx-fpm-alpine:latest
$ docker run -d --rm --read-only -p 8080:8080 --name pb privatebin/nginx-fpm-alpine
d657d234f0c80953d77793e792a657b8fb4ab4ba7e13b94022c92aee3c5328f4
$ docker logs pb
[05-May-2021 16:20:17] NOTICE: fpm is running, pid 39
[05-May-2021 16:20:17] NOTICE: ready to handle connections
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
$ docker version | grep -A2 -B0 Server
Server:
 Engine:
  Version:          20.10.2
```

**Comment by NoxInmortus** [comment]
Still same config, so yes running on armv7, but the bug displayed in #27 was just filling the log, in the current case the container can't even start.

And I though the bug has been solved, the latest image built is from today, is that really the same ?

**Comment by elrido** [comment]
The bug was not solved, as they decided not to backport the skalibs fix to Alpine 3.13 - we have to wait for the upcoming Alpine 3.14 release to get our armv7 image to work again. Annoyingly the image builds just fine, it simply doesn't start with the s6 version packaged in Alpine 3.13.

For now, on armv7 arch, please use the image tagged 1.3.4-alpine3.12.1 - I'd expect it to still work as we used the s6 overlay binaries back then:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/7dfe1b2bb4a11ac1d6732a94cea50517eb58864f/Dockerfile#L36-L47

Since we now use php 8, which isn't available in Alpine 3.12, I don't see it as an option to downgrade to that release and I don't want to maintain a separate dockerfile or special conditions that fetch the s6 overlay binaries directly from upstream, just for the armv7 build.

We might want to experiment with switching the image to edge, _only_ for the `latest` image tag (which gets refreshed nightly)? How risky would that be? Any opinions against that idea? Other ideas?

**Comment by NoxInmortus** [comment]
I was sure the bug was resolved, misread I guess, sorry about that.

Just tested the 1.3.4-alpine3.12.1  tag, it is working great indeed, will stay on this one for now.

Using alpine:edge could be a good idea, but _edge_ also means _not stable_ isnt it ? I would not myself use edge for `latest` tags as users not really wanting to experiment might just do that unintentionally and be confronted to edge bugs and immediately rising an issue here (like myself :grin:). But what about an `edge` tag ?

**Comment by elrido** [comment]
> Using alpine:edge could be a good idea, but edge also means _not stable_ isnt it ?

Yeah, I too wouldn't want to offer this as a production solution. Using bleeding edge software should be an informed choice. It can offer benefits, but is also even less tested.

In this particular case, the s6 packages were offered for the the first time in a stable release, so they may have been available in edge for some time before that, but no one seems to have noticed the bug on armv7 with it, before it got into the 3.13 release.

> But what about an `edge` tag ?

Now, that is a good idea! We could cover four use cases by adding it:
1. For those users that want to know exactly what they run at all times and want stable releases, they can use the full versioned tag (i.e. 1.3.4-alpine3.12.1) or even the image hash.
2. For users that want a stable release, but do want to be updated with security fixes, OS releases, etc. they can use the short version tag (i.e. 1.3.5) and have it pulled to check for updates and get the container restarted, if it changes.
3. For users that want the latest, but still stable, release we can continue to offer the latest tag.
4. And finally the edge tag would cover the use case for those users that are fine with using the bleeding edge of alpine.

I'll look into adding it to the nightly build schedule. Have to think, if there is a benefit to keeping a separate Dockerfile under version control or if we should just generate one on the fly, by replacing the version tag with `edge` in the `FROM` line.

**Comment by NoxInmortus** [comment]
> Now, that is a good idea! We could cover four use cases by adding it:
> 
>     1. For those users that want to know exactly what they run at all times and want stable releases, they can use the full versioned tag (i.e. 1.3.4-alpine3.12.1) or even the image hash.
> 
>     2. For users that want a stable release, but do want to be updated with security fixes, OS releases, etc. they can use the short version tag (i.e. 1.3.5) and have it pulled to check for updates and get the container restarted, if it changes.
> 
>     3. For users that want the latest, but still stable, release we can continue to offer the latest tag.
> 
>     4. And finally the edge tag would cover the use case for those users that are fine with using the bleeding edge of alpine.

Exactly my thinking !



> I'll look into adding it to the nightly build schedule. Have to think, if there is a benefit to keeping a separate Dockerfile under version control or if we should just generate one on the fly, by replacing the version tag with `edge` in the `FROM` line.

Idk about a `from` option from the command line, but maybe you can try using the `--build-arg` option and use it as a variable for  `FROM` ? Never tried tho

**Comment by elrido** [comment]
I went with the lazy `sed` option, for now. Should we find a reason to have the edge Dockerfile differ other than it's base image, we could still add it to version control later on.

Having this edge build gives us a way to detect changes in Alpine that might impact the image, before they reach the release based image.

**Comment by elrido** [comment]
FYI, with alpine 3.14 released, we got our images updated and the 1.3.5-alpine3.14, 1.3.5 and latest tags now all should contain the fixed s6 for armv7.
